### PR TITLE
Added comment explaining discrepancy in the field names.

### PR DESCRIPTION
**Pull request by pompon0**
When changing the crypto keys back from bn254 to bls12_381, we forgot to rename the proto fields as well. It is not feasible to do it now, because of backward compatibility, so I've just added comments to explain the discrepancy.

### CODE REVIEW

**Comment by brunoffranca** [comment]
Why can't we change it in a backwards compatible way?

**Comment by brunoffranca** [comment]
Also, is the field name visible only in code? I guess not, it's probably visible in logs too.

**Comment by pompon0** [comment]
we store commitqc in postgres in jsonb format

**Comment by brunoffranca** [comment]
Ok. But why can't we change the name?

**Comment by pompon0** [comment]
because the commitqc contains a signature which contains this field. Jsonb uses the text names in encoding.

**Review by brunoffranca — APPROVED** [review]
I still think we should find a way of changing the name that is backwards compatible. After all that's why we use protobuf. But since this is mostly a nuisance, I'll approve it anyway.

**Pull request merged**
